server:
    port: 8081

url:
    generate:
        token: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/realm
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    application:
        name: mykeycloak